import React from 'react';
import { Category, AITool } from './types';
import { ImageIcon, PencilIcon, VideoIcon, CodeIcon, BrainIcon, ChartIcon, MicIcon } from './components/icons/Icons';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'Tất cả' },
  { id: 'image', name: 'Tạo Hình Ảnh' },
  { id: 'text', name: 'Văn Bản & Viết Lách' },
  { id: 'video', name: 'Tạo Video' },
  { id: 'audio', name: 'Âm Thanh' },
  { id: 'marketing', name: 'Marketing' },
  { id: 'dev', name: 'Phát Triển (Sắp có)' },
];

export const AI_TOOLS: AITool[] = [
  {
    id: 'visioncraft',
    name: 'VisionCraft AI',
    category: 'Tạo Hình Ảnh',
    description: 'Tạo ra những hình ảnh tuyệt đẹp, độ phân giải cao từ các mô tả văn bản đơn giản. Hoàn hảo cho nghệ sĩ và nhà tiếp thị.',
    longDescription: 'VisionCraft AI là một công cụ tạo hình ảnh hàng đầu, cho phép bạn biến những ý tưởng phức tạp nhất thành hiện thực chỉ bằng vài từ. Sử dụng các mô hình khuếch tán tiên tiến, nó cung cấp khả năng kiểm soát chi tiết về phong cách, ánh sáng và bố cục, giúp bạn tạo ra các tác phẩm nghệ thuật độc đáo, hình ảnh sản phẩm chân thực hoặc các concept marketing đột phá.',
    price: '$29/tháng',
    tags: ['Thiết kế', 'Nghệ thuật', 'Sáng tạo'],
    icon: <ImageIcon className="w-8 h-8 text-cyan-400" />,
    status: 'active',
    features: [
      'Tạo ảnh từ văn bản với độ chính xác cao',
      'Nhiều mô hình nghệ thuật: tả thực, anime, 3D...',
      'Tùy chỉnh độ phân giải lên đến 4K',
      'Tính năng "Outpainting" để mở rộng hình ảnh',
      'Giao diện kéo-thả trực quan',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1679083216318-3c18084a9507?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1690161439243-7f6516081515?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1677759223599-0a8ca8c19b0a?q=80&w=800&auto=format&fit=crop',
    ],
    websiteUrl: '#',
  },
  {
    id: 'echovid',
    name: 'EchoVid',
    category: 'Tạo Video',
    description: 'Tạo video chất lượng chuyên nghiệp từ văn bản hoặc ý tưởng chỉ trong vài phút. Tích hợp sẵn kho cảnh quay và nhạc nền.',
    price: '$49/tháng',
    tags: ['Video', 'Mạng xã hội', 'Quảng cáo'],
    icon: <VideoIcon className="w-8 h-8 text-rose-400" />,
    status: 'active',
    fullscreen: true,
  },
  {
    id: 'script-pro',
    name: 'Kịch Bản Pro',
    category: 'Văn Bản & Viết Lách',
    description: 'Trợ lý AI giúp bạn sáng tạo kịch bản phim, video YouTube, và quảng cáo. Tự động tạo cốt truyện và phát triển nhân vật.',
    price: '$35/tháng',
    tags: ['Viết kịch bản', 'Sáng tạo', 'YouTube'],
    icon: <PencilIcon className="w-8 h-8 text-amber-400" />,
    status: 'active',
  },
  {
    id: 'voice-studio',
    name: 'Giọng Nói Studio',
    category: 'Âm Thanh',
    description: 'Chuyển đổi văn bản thành giọng nói AI tự nhiên, truyền cảm với nhiều ngôn ngữ và ngữ điệu khác nhau, bao gồm cả Tiếng Việt.',
    price: '$20/tháng',
    tags: ['Lồng tiếng', 'Podcast', 'Audiobook'],
    icon: <MicIcon className="w-8 h-8 text-teal-400" />,
    status: 'active',
  },
  {
    id: 'content-master',
    name: 'ContentMaster AI',
    category: 'Văn Bản & Viết Lách',
    description: 'Viết lại và tối ưu hóa nội dung của bạn để trở nên độc đáo, hấp dẫn và chuẩn SEO hơn mà không làm thay đổi ý chính.',
    price: '$19/tháng',
    tags: ['Viết lại', 'Nội dung', 'SEO'],
    icon: <PencilIcon className="w-8 h-8 text-amber-400" />,
    status: 'active',
  },
  {
    id: 'tuberank',
    name: 'TubeRank AI',
    category: 'Marketing',
    description: 'Phân tích và tối ưu hóa tiêu đề, mô tả, và từ khóa để video YouTube của bạn đạt thứ hạng cao nhất trên kết quả tìm kiếm.',
    price: '$39/tháng',
    tags: ['YouTube', 'SEO', 'Phân tích'],
    icon: <ChartIcon className="w-8 h-8 text-sky-400" />,
    status: 'active',
  },
  {
    id: 'codemate',
    name: 'CodeMate AI',
    category: 'Phát Triển (Sắp có)',
    description: 'Một lập trình viên cặp AI giúp bạn viết mã sạch hơn, nhanh hơn, sửa lỗi và học ngôn ngữ mới.',
    price: 'Sắp có',
    tags: ['Phát triển', 'Gỡ lỗi', 'Năng suất'],
    icon: <CodeIcon className="w-8 h-8 text-emerald-400" />,
    status: 'coming_soon',
  },
];
